### ISSUE TITLE
Error running a new project

### ISSUE THREAD

**Issue by ghost** [oelizondo/Sofia#16]
### How to reproduce

`sofia new Test`
`cd Test`
`sofia run`
### Output

``` console
[12:50:55] Using gulpfile ~/tmp/Test/gulpfile.js
[12:50:55] Starting 'sass-compile'...
[12:50:55] Finished 'sass-compile' after 18 ms
[12:50:55] Starting 'sanitize'...
[12:50:55] Finished 'sanitize' after 4.61 ms
[12:50:55] Starting 'js'...
[12:50:55] Finished 'js' after 2.03 ms
[12:50:55] Starting 'html'...
[12:50:55] Finished 'html' after 1.38 ms
[12:50:55] Starting 'serve'...
[12:50:55] Finished 'serve' after 9.62 ms
[12:50:55] Starting 'default'...
[12:50:55] Finished 'default' after 4.21 μs
livereload[tiny-lr] listening on 35729 ...
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1238:14)
    at listen (net.js:1274:10)
    at Server.listen (net.js:1370:5)
    at Function.listen (/home/mroutis/tmp/Test/node_modules/connect/index.js:217:24)
    at Object.<anonymous> (/home/mroutis/tmp/Test/node_modules/gulp-live-server/scripts/static.js:16:5)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
```

**Comment by oelizondo** [comment]
Make sure you run npm install!
